config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'diary' => 'diary#home'
  get 'diary/new' => 'diary#new'
  post 'diary/create' => 'diary#create'
  get 'diary/:id/edit' => 'diary#edit', as: :edit
  patch 'diary/:id/' => 'diary#update'
  get 'diary/:id/delete' => 'diary#delete'


#Api Controller
	namespace 'api' do
  		get 'diary' => 'diary#index'
  		get 'diary/:id' => 'diary#show'
  		post 'diary/new' => 'diary#create'
	end


end

app/models/diaryku.rb
class Diaryku < ApplicationRecord
	validates :nama, :catatan, :lokasi, :presence => true
	validates :nama, :catatan, :lokasi, :length => { :minimum => 2 }
	validates :nama, :catatan, :lokasi, :uniqueness => true
end

app/controllers/api/diary_controller.rb
module Api
	class DiaryController < ApplicationController
		protect_from_forgery except: :index
		def index
			diary = Diaryku.all
			render json: {status: 'ok', data: diary}
		end

		def show
			begin
			diary = Diaryku.find(params[:id])
			render json: {data: diary}
			rescue ActiveRecord::RecordNotFound
				render json: {status: 'not found'}
		end
		end

		def create
			diary = Diaryku.new(diary_params)
			if diary.save
				render json: {status: 'saved', data: diary}
			else
				render json: {status: 'failed'}
			end
		end

		private
		def diary_params 
    	params.permit(:nama, :catatan, :lokasi) 
  		end

  	end
end

app/controllers/diary_controller.rb
class DiaryController < ApplicationController
	def home
		@diary = Diaryku.all #query select * from
	end

	def new
		@diary = Diaryku.new
	end

	def create
		@diary = Diaryku.new(diary_params) #query insert into dan mengambil parameter diary_params
		if @diary.save
			redirect_to '/diary' 
			else
				render 'new'
			end
	end

	def edit
		@diary = Diaryku.find(params[:id]) #query select * from sesuai id
	end

	def update
		@diary = Diaryku.find(params[:id]) #query update sql
		if @diary.update(diary_params)
			redirect_to '/diary'
		else
			render '/diary'
		end
	end

	def delete
		@diary = Diaryku.find(params[:id]) #query delete from
		@diary.destroy
		redirect_to '/diary'

	end

	private 
  	def diary_params 
    	params.require(:diaryku).permit(:nama, :catatan, :lokasi) #kalau istilah kaya diframework php laravel ini $requestnya
  	end

end

app/views/diary/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Edit</title>
</head>
<body>
	<%= form_for @diary, url: {action: "update"},html: {class: "form"} do |s| %>
	 <p>
		<%= s.label(:nama) %>
		<%= s.text_field :nama %>
	</p>
	<p>
		<%= s.label(:catatan) %>
		<%= s.text_area :catatan %>
	</p>
	<p>
		<%= s.label(:lokasi) %>
		<%= s.text_field :lokasi %>
	</p>
	<p>
		<%= s.submit "Update" %>
	</p>
	<%  end %>
</body>
</html>

app/views/diary/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
</head>
<body>
<table align="center" border="1">
	<tr>
	
		<th>Nama Penulis</th>
		<th>Catatan</th>
		<th>Lokasi</th>
		<th colspan="2">Action</th>
	</tr>
	<% @diary.each do |s| %>
	<tr>
		<td><%= s.nama %></td>
		<td><%= s.catatan %></td>
		<td><%= s.lokasi %></td>
		<td><%= link_to "Edit", controller: "diary", action: "edit", id:s.id %></td>
		<td><%= link_to "Delete", controller: "diary", action: "delete", id:s.id %></td>
</tr>

	<% end %>
		<%= link_to 'Catatan baru', "new" %>

</table>


</body>
</html>

app/views/diary/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>New Data</title>
</head>
<body>
<h1>Create Rubby On Rails</h1>

<%= form_for @diary, url: diary_create_path()  do |s| %>
<% if @diary.errors.any? %>
	<% @diary.errors.full_messages.each do |message| %>
		<pre>
			<%= message %>
		</pre>
	<% end %>
<% end %>

	<p>
		<%= s.label(:nama) %>
		<%= s.text_field :nama %>
	</p>
	<p>
		<%= s.label(:catatan) %>
		<%= s.text_area :catatan %>
	</p>
	<p>
		<%= s.label(:lokasi) %>
		<%= s.text_field :lokasi %>
	</p>
	<p>
		<%= s.submit "Add" %>
	</p>



<% end %>
</body>
</html>